[workspace]
resolver = "3"
members = [
  "hecate",
  "mcp-server",
]

[workspace.package]
edition = "2024"
license-file = "../LICENSE"

[workspace.dependencies]
thiserror = "2.0.12"
anyhow = "1.0.98"
schemars = "0.9.0"
