[package]
name = "hecate"
version = "0.2.0"
edition = "2024"

[build-dependencies]
bindgen = "0.71.1"
cmake = "0.1.54"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
derive-alias = "0.1.1"
schemars = "0.8.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tera = {version = "1.20.0", default-features = false}
thiserror = "2.0.12"
anyhow = "1.0.98"
num-traits = "0.2.19"
lazy_static = "1.5.0"
itertools = "0.14.0"
indexmap = { version = "2.9.0", features = ["serde"] }
serde_yaml = "0.9.34"
typetag = "0.2.20"
dyn-clone = "1.0.19"
regex = "1.11.1"
uom = { version = "0.37.0", default-features = false, features = ["std", "si", "serde", "f64"] }
const_format = "0.2.34"
num = "0.4.3"

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2.100"


[target.'cfg(not(target_family = "wasm"))'.dependencies]
clap = { version = "4.5.36", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
rquickjs = {  git = "https://github.com/DelSkayn/rquickjs.git", version = "0.9.0", features = ["futures", "macro", "loader"] }
llrt_modules = { git = "https://github.com/awslabs/llrt.git", version = "0.5.1-beta", default-features = false, features = ["crypto", "console", "timers"] }
