[package]
name = "hecate"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "0.71.1"
cmake = "0.1.54"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
derive-alias = "0.1.1"
rquickjs = {  git = "https://github.com/DelSkayn/rquickjs.git", version = "0.9.0", features = ["futures", "macro", "loader"] }
llrt_modules = { git = "https://github.com/awslabs/llrt.git", version = "0.5.1-beta", default-features = false, features = ["crypto", "console", "timers"] }
tokio = { version = "1", features = ["full"] }
schemars = "0.8.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tera = {version = "1.20.0", default-features = false}
thiserror = "2.0.12"
anyhow = "1.0.98"
num-traits = "0.2.19"
lazy_static = "1.5.0"
itertools = "0.14.0"
indexmap = "2.9.0"
