[package]
name = "entity"
edition = "2024"
publish = false
rust-version.workspace = true


[dependencies]
sea-orm = { workspace = true }
hecate = { path = "../hecate"}
serde = { workspace = true }
schemars = { workspace = true }
