name: Release

on:
  push:
    branches: [ main ]
    paths:
      - 'hecate/**'
      - '.github/workflows/publish.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'test'
    steps: 
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      # - name: Run tests
      #   working-directory: hecate
      #   run: cargo test && cargo test --examples
  release:
    name: 'Release-plz release'
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ShaitanLyss' }}
    needs: test
    environment: cargo
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
          manifest_path: hecate/Cargo.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.repository_owner == 'ShaitanLyss' }}
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
          manifest_path: hecate/Cargo.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  # publish:
  #   runs-on: ubuntu-latest
  #   # needs: 'test'
  #   name: 'publish'
  #
  #   # Reference your environment variables
  #   environment: cargo
  #
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - dir: "/hecate/symbolic/"
  #           tag_prefix: "symrs-"
  #         - dir: "/hecate/hecate"
  #           tag_prefix: "hecate-"
  #         - dir: "/hecate/executor/"
  #           tag_prefix: "executor-"
  #         - dir: "/hecate/entity/"
  #           tag_prefix: "entity-"
  #         - dir: "/hecate/migration/"
  #           tag_prefix: "migration-"
  #         - dir: "/hecate/mcp-server/"
  #           tag_prefix: "mcp-server-"
  #
  #   steps:
  #     - uses: actions/checkout@master
  #     - run: echo ${{ matrix.dir }}
  #     - name: Run publish-action
  #       uses: tu6ge/publish-action@v0.4.6
  #       env:
  #         # This can help you tagging the github repository
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         # This can help you publish to crates.io
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  #       with:
  #         DIR: ${{ matrix.dir }}
  #         TAG_PREFIX: ${{ matrix.tag_prefix }}
