name: Publish to Cargo

on:
  push:
    branches: [ main ]
    paths:
      - 'hecate/**'
      - '.github/workflows/publish.yml'

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   name: 'test'
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Run tests
  #       working-directory: hecate
  #       run: cargo test && cargo test --examples
  publish:
    runs-on: ubuntu-latest
    # needs: 'test'
    name: 'publish'

    # Reference your environment variables
    environment: cargo

    strategy:
      fail-fast: false
      matrix:
        include:
          - dir: "hecate/symbolic/"
            tag_prefix: "symrs-"
          - dir: "hecate/hecate"
            tag_prefix: "hecate-"
          - dir: "hecate/executor/"
            tag_prefix: "executor-"
          - dir: "hecate/entity/"
            tag_prefix: "entity-"
          - dir: "hecate/migration/"
            tag_prefix: "migration-"
          - dir: "hecate/mcp-server/"
            tag_prefix: "mcp-server-"

    steps:
      - uses: actions/checkout@master
      - name: Run publish-action
        uses: tu6ge/publish-action@v0.4.6
        env:
          # This can help you tagging the github repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This can help you publish to crates.io
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          DIR: ${{ matrix.dir }}
          TAG_PREFIX: ${{ matrix.tag_prefix }}
