name: Publish to Cargo

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'test'
    steps:
      - uses: actions/checkout@master
      - name: Run tests
        working-directory: hecate
        run: cargo test && cargo test --examples
  publish:
    runs-on: ubuntu-latest

    name: 'publish'

    # Reference your environment variables
    environment: cargo

    strategy:
      fail-fast: false
      matrix:
        include:
          - dir: "/hecate-symrs/"
            tag_prefix: "symrs-"
          - dir: "/hecate-lib/"
            tag_prefix: "hecate-"
          - dir: "/hecate-executor/"
            tag_prefix: "executor-"
          - dir: "/hecate-entity/"
            tag_prefix: "entity-"
          - dir: "/hecate-migration/"
            tag_prefix: "migration-"
          - dir: "/hecate-mcp-server/"
            tag_prefix: "mcp-server-"

    steps:
      - uses: actions/checkout@master

      # Use caching to speed up your build
      - name: Cache publish-action bin
        id: cache-publish-action
        uses: actions/cache@v3
        env:
          cache-name: cache-publish-action
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v0.2.0

      # install publish-action by cargo in github action
      - name: Install publish-action
        if: steps.cache-publish-action.outputs.cache-hit != 'true'
        run:
          cargo install publish-action --version=0.2.0
      
      - name: Run publish-action
        id: publish-action
        run:
          publish-action
        env:
          # This can help you tagging the github repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This can help you publish to crates.io
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          DIR: ${{ matrix.dir }}
          TAG_PREFIX: ${{ matrix.tag_prefix }}
