name: Rust Unit Tests & Check Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 23
        cache: 'pnpm'
        cache-dependency-path: ./hecate/js/pnpm-lock.yaml
        

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta



    - name: Run cargo test
      run: cargo test
      working-directory: ./hecate

  # Check formatting with rustfmt
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
        with:
          manifest-path: ./hecate/Cargo.toml
